### ISSUE TITLE
Server thread ends after corrupting OpCode

### ISSUE THREAD

**Issue by Fisher888** [lexibrown/SYSC3303-TFTP#2]
fails when ErrorSim thread = opcode ack 1 wrq (probably on others as well)

will try to update the server tomorrow :)

**Comment by scotthanton** [comment]
Isn't it suppose to end if it receives the wrong opcode / corrupted packet?

**Comment by scotthanton** [comment]
I thought it was

Incoming packet from unknown source ID, ignore packet and continue
Incoming packet with undesired op code or corrupted contents, terminate.

**Comment by Fisher888** [comment]
LOL yeah you're right.

**Comment by Fisher888** [comment]
should be all good then
