### ISSUE TITLE
Server doesn't terminate when receiving wrong block#

### ISSUE THREAD

**Issue by Fisher888** [lexibrown/SYSC3303-TFTP#3]
The client/server when receiving a corrupt block#, times out and resends the last ACK -- continuing the file transfer. Totally legit for a real world scenario and probably how and actual client/server should work; but does not satisfy the following criteria:

"Incoming packet with undesired op code or corrupted contents, terminate."

What do you think?

**Comment by scotthanton** [comment]
What's a corrupted block number consist of? If it's just a different block number then the desired one there's no way to tell the difference between a corrupted block or a delayed packet with an undesired block number. I think we should just resend if the packet has a valid block number even if it's been corrupted.

**Comment by Fisher888** [comment]
I agree.
